network_monitor:
  known_ports: [22, 80, 443, 53, 8080]
  scan_interval: 5

file_monitor:
  linux_paths:
    - "/etc/passwd"
    - "/etc/shadow"
  windows_paths:
    - "C:/Users/benne/Documents/test_watch.txt"
    - "C:/Windows/System32/drivers/etc/hosts"
  scan_interval: 5

process_monitor:
  blacklisted_processes:
    - "netcat"
    - "ncat"
    - "nmap"
    - "hydra"
    - "msfconsole"
    - "python -m http.server"
    - "minerd"
    - "xmrig"
    - "cmd.exe"
    - "powershell.exe"
    - "malware_sample"
  scan_interval: 5

huntsman:
  scan_interval: 300  # 5 minutes

intelli_spider:
  sync_interval: 43200  # Every 12 hours
  enable_threatfox: true
  enable_malwarebazaar: true
  enable_otx: false  # (Enable later once OTX is fully set up)
